export enum Tech {
  'JS' = 'JavaScript',
  'Apex' = 'APEX',
  'Aws' = 'AWS',
  'Docker' = 'Docker',
  'DynamoDB' = 'DynamoDB',
  'ElectronJS' = 'ElectronJS',
  'Git' = 'Git',
  'GraphQL' = 'GraphQL',
  'Memcached' = 'Memcached',
  'MongoDB' = 'MongoDB',
  'NodeJs' = 'Node.js',
  'PHP' = 'PHP',
  'PostgreSQL' = 'PostgreSQL',
  'React' = 'React',
  'Redis' = 'Redis',
  'Rest' = 'REST',
  'TypeScript' = 'TypeScript',
  'Shopify' = 'Shopify',
  'Serverless' = 'Serverless',
  'Tdd' = 'TDD',
  'Cypress' = 'Cypress',
  'StoryBook' = 'StoryBook',
  'MySql' = 'MySQL',
  'DigitalOcean' = 'Digital Ocean',
  'Svn' = 'SVN',
  'WordPress' = 'WordPress',
}

export const RESUME_URL = 'https://resume.io/r/UX7zp7chr';